language: python
python: 3.6
sudo: required

services:
  - docker

before_install:
  - docker pull ubuntu:16.04
  - docker ps -a

install:
  - pip install -q testinfra --use-wheel

script:
  - docker build -t teknoradio/youtube .
  - docker run --rm --entrypoint="" --name youtube teknoradio/youtube /bin/bash -c "which ffmpeg" | grep -q /usr/local/bin/ffmpeg
  - py.test --connection=docker -v

notifications:
  email : false
